### PR TITLE
Added Windows install instructions for PHP sniffer

### PR DESCRIPTION
**Pull request by glye**

### CODE REVIEW

**Comment by andrerom** [comment]
I guess the instructions by now could be changed to propose use of composer to install it, hence avoiding having system specific instructions, and avoid dealing with pear.

**Comment by yannickroger** [comment]
+1
It gets the job done, until we have a composer based version (for all OS). Should we create a doc issue ?

**Comment by andrerom** [comment]
well, yes, but it also means we'll never do it ;)

**Comment by mere-teresa** [comment]
Why never ?
You can create a Doc Issue and you have to defend it for the next Sprint :)

**Comment by andrerom** [comment]
+1

**Pull request merged**
